### ISSUE TITLE
longitude, latitude, altitude

### ISSUE THREAD

**Issue by MichaelWallace30** [NGCP/CommProto-MessageStandards2017#3]
VehicleWaypointCommand(uint16_t vehicle_id = 0,
		float latitude = 0,
		float longitude = 0,
		float altitude = 0) 

this should be x,y,z 
currently y,x,z
any use should be in that order unless Im mistaken

**Comment by Jester565** [comment]
I can change the code in PacketGen, should be an easy fix

**Comment by CheezBoiger** [comment]
I don't think it matters but lulz, picky Wallace they call em... the variable names themselves are quite clear.

**Comment by Jester565** [comment]
I made a pull request that should resolve this issue

**Comment by CheezBoiger** [comment]
Awesome! Now comes the hard part... having everyone who already pulled this repo update their packet lulz.

**Comment by MichaelWallace30** [comment]
Its only GCS who is our test platform

**Comment by CheezBoiger** [comment]
This was still highly unnecessary...

**Comment by MichaelWallace30** [comment]
Your face is unnecessary
