### ISSUE TITLE
class needs to be public

### ISSUE THREAD

**Issue by MichaelWallace30** [NGCP/CommProto-MessageStandards2017#6]
Some reason all the class needs to be public

So 
class VehicleGlobalPosition : ABSPacket

To
public class VehicleGlobalPosition : ABSPacket

For all csharp

**Comment by Jester565** [comment]
I'll fix this and recreate all the packets using PacketGen in about 2
hours. Sorry about that.

**Comment by CheezBoiger** [comment]
That's coo I forgot about the modifier as well lulz
