### ISSUE TITLE
long , lat, alt

### ISSUE THREAD

**Issue by MichaelWallace30** [NGCP/CommProto-MessageStandards2017#7]
This is probably my oversight. 

Im noticing longitude, latitude, altitude is some times an Int32 and other times its Single for CS.

Probably all should be floats minimum precision. Going to have to look through all the files.

**Comment by CheezBoiger** [comment]
This is not our issue. Tell faculty, or platforms, to keep their packet standards consistent. We only do whats on paper

**Comment by Jester565** [comment]
I'll fix this too, I'll change all of them to floats

**Comment by CheezBoiger** [comment]
@MichaelWallace30 We need to update the standards paper because long, lat, and alt are different on certain packets

**Comment by MichaelWallace30** [comment]
Yeah will blame Amy I just copied her work and I didn't even think twice about it.

**Comment by Jester565** [comment]
So I'm changing the standards paper.  In Vehicle Global Position, the units for longitude and latitude are Lat\*1E7.  While in Vehicle Inertial State, the units are rads.  Are we changing all the units to rads or will also be using floats to store the units Lat\*1E7?

**Comment by MichaelWallace30** [comment]
You can make the decision every thing should be uniform

**Comment by Jester565** [comment]
I've also noticed other variables are using different types and units.
VehicleIntertialState::Roll_Rate is float_32 in rad/s and VehicleGlobalPosition::Roll_Rate is int_16 millirad/s.
There are several other examples.  Should I change VehicleGlobalPosition::Roll_Rate (and other variables with type conflicts) to float_32 or leave it  like it is.

**Comment by Jester565** [comment]
What about my last question? Shouldn't we make all variables consistent? Right now there are still some different units and types for variables with the same name.

**Comment by MichaelWallace30** [comment]
Sorry didnt read it. Yeah they should be consistent. Otherwise ill complain about it once i notice. Any thing that doesn't match is a mistake.

**Comment by Jester565** [comment]
# Standardized Units
| var | type | unit | changes |
| ----------- | -------- | ------- | ------|
| \*altitude\* | float32/64 | meters | no changes |
| \*longit\* | float32 | radians | no changes |
| \*latitude\* | float32 | radians | no changes |
| \*angle\* | float32/64 | radians | there used to be a degree |
| \*accel\* | float32 | m/s | there used to be int16 with units of g/1000 |
| \*speed\* | float32 | m/s | there used to int16 with units of m/s * 100 |
| \*rate\* | float32 | radians/second | there used to be int16 in millirad/second |

Those \*s are wildcards.  For example, both north_speed and x_speed were changed to m/s even though x_speed used to be int16 with units of g/1000 before.  If this is too much of a change tell me.  If not, expect a fix in 15 minutes.

**Comment by MichaelWallace30** [comment]
This is fine
